# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stations.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import QDialog, QApplication
import time
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtCore import Qt as Qt_library


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.centralwidget = None
        self.tableWidget = None
        self.water_stations_label = None
        self.statusBar = None
        self.toolBar = None
        self.Database_menu_refresh = None
        self.pushButton = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 815)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.water_stations_label = QtWidgets.QLabel(self.centralwidget)
        # some changes have made here - ui cosmetics
        self.water_stations_label.setGeometry(QtCore.QRect(130, 60, 800, 101))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(30)
        self.water_stations_label.setFont(font)
        self.water_stations_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.water_stations_label.setAlignment(Qt_library.AlignCenter)
        self.water_stations_label.setObjectName("water_stations_label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(250, 170, 550, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        # My change of alignment - ui cosmetics
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        item.setBackground(QtGui.QColor(159, 185, 181))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        # My change of column length - ui cosmetics
        self.tableWidget.setColumnWidth(0, 100)

        item = QtWidgets.QTableWidgetItem()
        # My change of alignment - ui cosmetics
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        # My change of column length - ui cosmetics
        self.tableWidget.setColumnWidth(1, 100)

        item = QtWidgets.QTableWidgetItem()
        # My change of alignment - ui cosmetics
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        # My change of column length - ui cosmetics
        self.tableWidget.setColumnWidth(2, 100)

        item = QtWidgets.QTableWidgetItem()
        # My change of alignment - ui cosmetics
        item.setTextAlignment(QtCore.Qt.AlignLeft)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        # My change of column length - ui cosmetics
        self.tableWidget.setColumnWidth(3, 220)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1097, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

    # HERE I ADDED MANUALLY FUNCTIONALITY TO THE STATIC UI
        # Adding a refresh button
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 650, 120, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")

        # loading the static UI (connecting the widgets to the main window)
        self.retranslateUi(MainWindow)

        # Adding functionality to the pushButton (refreshing button)
        self.pushButton.clicked.connect(self.load_data)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Manipulating the automatically generated code here
        self.tableWidget.setHorizontalHeaderLabels(["station_id", "alarm_1", "alarm_2", "update_time"])
        self.load_data()

    # This function created by me - getting data from sqlite and inserting into the table and refreshing the table:
    def load_data(self):
        conn = sqlite3.connect("all_stations.sqlite")
        cur = conn.cursor()
        query = "SELECT * FROM station_status;"

        self.tableWidget.setRowCount(0)
        table_row_index = 0
        try:
            for row in cur.execute(query):
                # print(row)
                self.tableWidget.insertRow(table_row_index)
                self.tableWidget.setItem(table_row_index, 0, QtWidgets.QTableWidgetItem(str(row[0])))
                self.tableWidget.setItem(table_row_index, 1, QtWidgets.QTableWidgetItem(str(row[1])))
                self.tableWidget.setItem(table_row_index, 2, QtWidgets.QTableWidgetItem(str(row[2])))
                self.tableWidget.setItem(table_row_index, 3, QtWidgets.QTableWidgetItem(row[3]))

                table_row_index += 1
                # self.tableWidget.setRowCount(table_row_index)
        except sqlite3.OperationalError as err:
            print(f"Error message from UI: {err}\n It will be created automatically")

        conn.close()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.water_stations_label.setToolTip(_translate("MainWindow", "Water Station Alarm Reports"))
        self.water_stations_label.setStatusTip(_translate("MainWindow", "Water Station Alarm Reports"))
        self.water_stations_label.setText(_translate("MainWindow", "Water Stations Alarm Reports"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Station ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Last Update Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Alarm 1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Alarm 2"))

    # Adding a refresh button
        self.pushButton.setToolTip(_translate("MainWindow", "Fetching data from the DB and inserting to the table"))
        self.pushButton.setStatusTip(_translate("MainWindow", "Fetching data from the DB and inserting to the table"))
        self.pushButton.setText(_translate("MainWindow", "Refresh Data"))


def main_flow():

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.load_data()
    MainWindow.show()
    sys.exit(app.exec_())


# if __name__ == "__main__":

#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     ui.load_data()
#     MainWindow.show()
#     sys.exit(app.exec_())


